{
  braking_coeff: 1,
  curvature_coefficient: 1.0,
  heading_coefficient: 1.0,
  deceleration_near_hard_buffer: 1,
  dist_to_go: 1.0,
  error_to_goal: 0.5,
  frequency: 50,
  hard_acceleration_limit: false,
  is_benchmark_mode: false,
  lat_gain: 0,
  min_linear_speed: 0.25,
  num_of_cycles_for_benchmark: 10000,
  rs_stop_turn_angle: 0.5,
  rs_v_gain: 1,
  rs_v_max: 1,
  rs_v_threshold: 0.5,
  rs_w_gain: 1.0,
  rs_w_max: 1.0,
  rs_dist_to_go: 0.7,
  stop_turn_angle: 1.25,
  stop_yaw_to_check_angle: 0.8,
  use_prediction: true,
  prediction_min_trajectory_length: 2.0,
  use_rotation: false,
  v_accel: 1.0,
  v_decel: 2.0,
  v_decel_max: 3.0,
  v_gain: 1.0,
  v_threshold: 1.5,
  w_accel: 1,
  w_d_gain: 3.0,
  w_gain: 1.5,
  w_i_gain: 0.0,
  w_integrator_max: 0.0,
  w_max: 1.0,
  wheel_track: 1.65,
  is_using_positive_ff: false,
  wpff_coeff: 0.1,
  is_using_diff_filter: true,
  d_t: 0.02,
  alpha: 0.1,
  beta: 0.0000001
}
