filter_x_front: 0.4
filter_x_rear: 0.4
filter_y_left: 0.4
filter_y_right: 0.4
occ_free: 0.4
occ_obst: 0.95
occ_prior: 0.5
only_obstacles: false
publish_rate: 10
queue_size: 15
raycast_type: 4
resolution: 0.2  # meters
upd_roi_xy: 20.0  # meters
size_xy: 600  # cells
t_overhang: 1.5
t_positive: 0.3
# free_classes: [8, 9, 10, 11, 12, 13, 14, 15, 16, 24, 25, 28, 64, 65]
# dynamic_classes: [2, 20, 21, 22, 23, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]

# position measured from center of local map to lidar's center (from calibration file)
# if ang_start == ang_end then ang_start = -180 deg., ang_end = 180 deg. 
# WARNING: angle start must be less then angle end
sensor:
  position: [ 0., 0.]                     # [x, y], meters
  global_sector: [0., 0.]                 # [angle start, angle end], degrees
  global_angle_resolution: 0.2            # raycast angle resolution, degrees
  min_points_range: 0.                    # meters
  global_raycast_range: 60.0              # meters
# for sectors field (raycast parameter per sector):
# [angle start, angle end, first half axis, second half axis, angle resolution (not realized yet), maximal range (not realized yet)]
  # sectors: 
  #   "0": [110., 250., 2., 3., 5.2, 60.]   # forward direction - 180
  #   "1": [20., 110., 3.5, 2.5, 0.2, 60.]  # right direction - 90
  #   "2": [-25., 25., 5., 3., 0.2, 60.]    # backward direction - 0
  #   "3": [250., 340., 3.5, 2.5, 0.2, 60.] # left direction - 270
  
