{
  RESET_CURRENT_TASK: false, 
  differ_between_paths: 20, 
  dist_to_point_for_replan: 7.0,
  dist_to_trajectory_for_replan: 5.0, 
  fixed_frame_id: 'local_map', 
  frequency: 5, 
  length_to_goal: 3.0,
  position_time_delay: 0.5, 
  map_time_delay: 1, 
  nearest_route_point_mode: false,
  planner_time_delay: 1.0,
  planning_space: 1, 
  pred_dist_coeff: 3.0, 
  show_additional_debug_info: false, 
  time_to_replan: 7, 
  vel_depend_to_replan: true,
  vel_depend_to_replan_for_key_point: false,
  switch_to_real_vect_space: false,
  switch_to_reeds_shepp_space: true,
  path_calculation_before_replanning: true,
  queue_size_occ_grid: 5, 
  queue_size_odom: 10,
  route_follow_mode: false,
  publish_route_as_trajectory: false,
  length_of_segment_to_follow: 120.0,
  valid_len_of_segment_to_visit: 10,
  strict_follow: false,
  publish_rf_debug_points: true,
  feasible_edges_threshold: 0.5,
  should_delete_shorts: false,
  time_threshold_to_force_update: 3.0
}